/* ============================================================
   agent/implement/preflight.mjs — the ten things that must be true
   before a line is written

   SESSION 18 lists them: the proposal ID exists; the proposal is in
   an approved state; the approval is attributable to an authorized
   human or an explicitly permitted autonomy policy; the scope is
   defined; the permitted files are defined; provenance is complete;
   the required tests are defined; the risk level is defined; and
   rollback is available.

   FOUR PROPERTIES OF THE IMPLEMENTATION HERE.

   EVERY GATE IS MECHANICAL. Each returns pass or fail from something
   read out of the record, never from a judgement about it. There is
   no gate that says "the change looks reasonable" — a gate a
   sufficiently confident agent can talk its way past is not a gate.

   ALL TEN RUN, ALWAYS. It would be cheaper to stop at the first
   failure, and it would produce a worse report: a proposal that
   fails four gates should be told so once rather than four times a
   day apart. `preflight()` returns the whole set.

   NONE OF THEM CAN BE PASSED BY ARGUMENT. `preflight()` takes a
   proposal id and reads everything else. It has no `skip`, no
   `assumeApproved`, and no `permittedFiles` parameter — the whole
   point of the ten is that the thing being constrained does not get
   to supply the constraint.

   A FAILING GATE IS A REFUSAL, NOT AN ERROR. It comes back as a
   record with the reason and what would close it, in the same shape
   every other agent here uses for something it could not establish.
   ============================================================ */

import { deriveApproval, IMPLEMENTABLE, proposalFingerprint } from './ledger.mjs';
import { permittedFiles, touchesLegalRecord, requiresBrowserQA } from './scope.mjs';
import { getContract } from '../schemas/registry.mjs';
import { validate } from '../schemas/validate.mjs';
import { REQUIRED_VALIDATORS, AUTONOMY_CLASSES } from '../schemas/types.mjs';

export const GATES = [
  'proposal_exists',
  'proposal_valid',
  'approved',
  'approval_attributable',
  'scope_defined',
  'permitted_files_defined',
  'provenance_complete',
  'required_tests_defined',
  'risk_defined',
  'rollback_available',
];

const pass = (gate, why, data = {}) => ({ gate, ok: true, why, ...data });
const fail = (gate, why, closes, data = {}) => ({ gate, ok: false, why, closes, ...data });

/**
 * @param {string} proposalId
 * @param {{records?:object, ledger?:object}} ctx
 * @returns {{proposal_id:string, ok:boolean, gates:object[], failed:object[],
 *            approval:object, scope:object|null, proposal:object|null}}
 */
export function preflight(proposalId, { records, ledger } = {}) {
  const approval = deriveApproval(proposalId, { records, ledger });
  const proposal = approval.proposal;
  const gates = [];

  /* 1 ---------------------------------------------------- exists */
  gates.push(proposal
    ? pass('proposal_exists', `"${proposalId}" is a ${proposal.contract} produced by ${proposal.agent}`)
    : fail('proposal_exists', `no record store holds a proposal with id "${proposalId}"`,
      'run the producing agent so the proposal exists as a record, then decide it. An id in a prompt is not a proposal.'));

  if (!proposal) return assemble(proposalId, gates, approval, null, null);

  /* 2 ---------------------------------------------- still valid */
  let contract = null;
  try { contract = getContract(proposal.contract); } catch { /* reported below */ }
  const errs = contract ? validate(proposal, { allowSimulated: false }) : [`"${proposal.contract}" is not a registered contract`];
  gates.push(errs.length === 0
    ? pass('proposal_valid', `the record satisfies ${proposal.contract} under the gate in agent/schemas/validate.mjs, re-checked now rather than trusted from when it was written`)
    : fail('proposal_valid', `the record no longer satisfies its own contract: ${errs.slice(0, 4).join('; ')}`,
      'the proposal has to be regenerated by the agent that owns it. An implementation agent does not repair a proposal — repairing it would make it a proposal nobody approved.', { errors: errs }));

  if (contract && contract.kind !== 'proposal') {
    gates.push(fail('proposal_exists', `"${proposalId}" is a ${proposal.contract}, whose contract kind is "${contract.kind}", not "proposal"`,
      'name a proposal. A finding, a record or an observation is not something to implement.'));
  }

  /* 3 -------------------------------------------------- approved */
  gates.push(IMPLEMENTABLE.includes(approval.state)
    ? pass('approved', approval.why, { state: approval.state })
    : fail('approved', `approval state is "${approval.state}": ${approval.why}`,
      approval.state === 'pending'
        ? 'a human decides it: node agent/implement/cli.mjs decide --proposal <id> --grant --by "<name>". Nothing an agent writes into agent/records/ can substitute.'
        : approval.state === 'void_scope_changed'
          ? 'the proposal changed after it was decided. It goes back for a fresh decision against the scope it now has.'
          : 'the decision has to come from a person who is not an agent in this system, against a proposal that exists.',
      { state: approval.state, discarded: approval.discarded }));

  /* 4 ------------------------------------- attributable, and to whom */
  const d = approval.decision;
  const attributable = Boolean(d && d.decided_by && d.decided_at && d.proposal_sha256);
  const bindingHolds = Boolean(d && d.proposal_sha256 === proposalFingerprint(proposal));
  gates.push(attributable && bindingHolds
    ? pass('approval_attributable', `decided by ${d.decided_by} at ${d.decided_at}, bound to proposal fingerprint ${d.proposal_sha256.slice(0, 12)}`, { decided_by: d.decided_by })
    : fail('approval_attributable',
      d ? `the decision is not fully attributable: decided_by=${d.decided_by ?? 'null'}, decided_at=${d.decided_at ?? 'null'}, fingerprint ${bindingHolds ? 'holds' : 'does not match the proposal as it now stands'}`
        : 'there is no decision to attribute',
      'an approval carries who, when, and what exactly they were approving. docs/AGENT-ROLES.md H4: where a link is missing, the record says so rather than implying a complete chain.'));

  /* 5 ----------------------------------------------- scope defined */
  const ops = proposal.proposed_change?.operations ?? [];
  const summary = proposal.proposed_change?.summary;
  gates.push(ops.length > 0 && summary
    ? pass('scope_defined', `${ops.length} operation(s) under one summary: "${summary}"`, { operations: ops.length })
    : fail('scope_defined', ops.length === 0 ? 'proposed_change.operations is empty' : 'proposed_change has no summary',
      'a proposal with no operations is a suggestion. It names what it would change, one edit at a time.'));

  /* An operation with a null `proposed` is a FINDING dressed as an
     operation — several agents here emit exactly that on purpose,
     because they observe and do not draft. It cannot be implemented,
     and saying why is more use than a generic scope failure. */
  const undrafted = ops.filter((o) => o.op !== 'remove' && (o.proposed === null || o.proposed === undefined));
  if (undrafted.length) {
    gates.push(fail('scope_defined', `${undrafted.length} of ${ops.length} operation(s) carry a null "proposed" value`,
      `the producing agent named a problem and deliberately drafted no value — agent/ux/ and agent/proposals/editorial/ both do this, and it is right: what the site should say is not an agent's decision. Somebody has to write the value before anything can apply it.`,
      { undrafted: undrafted.map((o) => o.target).slice(0, 6) }));
  }

  /* 6 ------------------------------------- permitted files defined */
  const scope = permittedFiles(proposal);
  gates.push(scope.permitted.length > 0 && scope.refusals.length === 0
    ? pass('permitted_files_defined', `${scope.permitted.length} permitted path(s), derived from the proposal's own operations and affected entities`, { permitted: scope.permitted })
    : fail('permitted_files_defined',
      scope.refusals.length
        ? `the proposal names ${scope.refusals.length} path(s) this agent may never write: ${scope.refusals.map((r) => r.path).join(', ')}`
        : 'no repository path can be derived from the proposal',
      scope.refusals.length
        ? scope.refusals.map((r) => `${r.path}: ${r.why}`).join(' · ')
        : 'the proposal has to name the files it touches. A permitted set nobody can derive is a permitted set nobody can enforce.',
      { permitted: scope.permitted, refusals: scope.refusals }));

  /* 7 ------------------------------------- provenance complete */
  const ev = proposal.evidence ?? [];
  const ep = proposal.epistemic ?? {};
  const realEvidence = ev.filter((e) => e.kind !== 'absent');
  const blocking = (ep.unresolved ?? []).filter((u) => u.blocks);
  const provenanceOk = ev.length > 0 && (realEvidence.length > 0 || (ep.unresolved ?? []).length > 0);
  gates.push(provenanceOk && blocking.length === 0
    ? pass('provenance_complete', `${realEvidence.length} evidence reference(s), ${(ep.fact ?? []).length} fact(s), ${(ep.inference ?? []).length} inference(s), ${(ep.unresolved ?? []).length} open question(s), none blocking`)
    : fail('provenance_complete',
      blocking.length
        ? `${blocking.length} blocking open question(s): ${blocking.map((u) => u.question).slice(0, 3).join(' · ')}`
        : 'the proposal carries no evidence at all, and does not say that it has none',
      blocking.length
        ? `an unresolved entry with blocks=true says nothing downstream may proceed until it is closed. ${blocking.map((u) => u.missing).slice(0, 3).join(' · ')}`
        : 'evidence is not optional and "absent" is a first-class kind. A record that stands on nothing says so in its own body.',
      { blocking: blocking.map((u) => ({ question: u.question, missing: u.missing, absence_kind: u.absence_kind })) }));

  /* 8 ------------------------------------- required tests defined */
  const reqs = proposal.validation_requirements ?? [];
  const named = new Set(reqs.map((r) => r.command ?? '').join(' ').match(/tools\/[a-z0-9-]+\.mjs/g) ?? []);
  const touched = scope.permitted;
  const needsAllFour = touched.some((p) => /^(data\/|i18n\/|js\/|css\/|tools\/)/.test(p) || p.endsWith('.html') || p === 'app.js' || p === 'style.css');
  const missingValidators = needsAllFour ? REQUIRED_VALIDATORS.filter((v) => !named.has(v)) : [];
  gates.push(reqs.length > 0 && missingValidators.length === 0
    ? pass('required_tests_defined', `${reqs.length} validation requirement(s)${needsAllFour ? ', all four validators among them' : ''}`, { requirements: reqs.length })
    : fail('required_tests_defined',
      reqs.length === 0 ? 'validation_requirements is empty' : `a change touching ${touched.filter((p) => /^(data\/|i18n\/|js\/|css\/|tools\/)/.test(p) || p.endsWith('.html')).join(', ')} names ${missingValidators.length} of the four validators nowhere: ${missingValidators.join(', ')}`,
      'AGENTS.md: run all four before and after any change to data, markup, styles or scripts. A proposal that does not name them has not said how anyone would know it is safe.',
      { missing: missingValidators }));

  /* 9 ----------------------------------------------- risk defined */
  const riskOk = Boolean(proposal.risk) && AUTONOMY_CLASSES.includes(proposal.autonomy_class);
  gates.push(riskOk
    ? pass('risk_defined', `risk "${proposal.risk}", autonomy class "${proposal.autonomy_class}"`, { risk: proposal.risk, autonomy_class: proposal.autonomy_class })
    : fail('risk_defined', `risk=${proposal.risk ?? 'null'}, autonomy_class=${proposal.autonomy_class ?? 'null'}`,
      'both are required fields on every proposal contract. A proposal that cannot say what it costs if it is wrong has not been thought about.'));

  /* 10 ------------------------------------------ rollback available */
  const rb = proposal.rollback_plan ?? {};
  const rollbackOk = Boolean(rb.method) && (rb.steps ?? []).length > 0 && Boolean(rb.verification)
    && (rb.method !== 'not_reversible');
  gates.push(rollbackOk
    ? pass('rollback_available', `${rb.method}, ${rb.steps.length} step(s), verified by: ${rb.verification}`, { method: rb.method })
    : fail('rollback_available',
      rb.method === 'not_reversible'
        ? `the proposal's own rollback plan is "not_reversible"${rb.irreversible_reason ? `: ${rb.irreversible_reason}` : ''}`
        : `rollback_plan is incomplete: method=${rb.method ?? 'null'}, ${(rb.steps ?? []).length} step(s), verification=${rb.verification ? 'stated' : 'null'}`,
      'docs/AUTONOMY-POLICY.md §4: every automated change must have a rollback path identified BEFORE the change is made, naming what is reverted, by what command, and how the revert is confirmed. A change whose rollback path cannot be stated is not made.'));

  const legal = touchesLegalRecord(scope.permitted);
  const browser = requiresBrowserQA(scope.permitted);

  return assemble(proposalId, gates, approval, proposal, {
    ...scope,
    touches_legal_record: legal,
    requires_browser_qa: browser,
  });
}

function assemble(proposalId, gates, approval, proposal, scope) {
  /* A gate named twice (scope_defined can be) fails if either
     instance failed. Deduplicated by name for the summary, kept whole
     in `gates` so nothing is lost. */
  const failed = gates.filter((g) => !g.ok);
  return {
    proposal_id: proposalId,
    ok: failed.length === 0,
    gates,
    failed,
    passed: gates.filter((g) => g.ok),
    approval,
    proposal,
    scope,
    /* The one sentence a caller needs. Never "looks fine". */
    summary: failed.length === 0
      ? `all ${GATES.length} gates pass; ${proposal.contract} "${proposalId}" may be implemented within ${scope.permitted.length} permitted path(s)`
      : `${failed.length} gate(s) refuse "${proposalId}": ${[...new Set(failed.map((f) => f.gate))].join(', ')}`,
  };
}
