/* The one source of the site footer and the no-JS notice.
   Both are written into the markup of every page rather than rendered by
   js/shell.js, because a statement of non-affiliation that only appears
   when JavaScript runs is not a statement of non-affiliation. The cost of
   that choice is seven copies; tools/design-qa.mjs checks they are
   identical, so they cannot drift.

   Run:  node tools/_footer.mjs        (from the repository root) */

import { readFileSync, writeFileSync } from 'node:fs';

/* The deployed origin. Canonical, og:url and the social tags are all built
   from this, so it is changed here and nowhere else. If the site moves,
   change this line and re-run. */
export const BASE = 'https://andreatosti2001.github.io/Eu-Digital-Policy/';

export const FOOTER = `<footer class="site-foot">
<div class="sf-inner">
<p class="sf-disclaimer"><b>Independent project.</b> This is an independent, non-commercial
analysis. It is not affiliated with, endorsed by or sponsored by the European Commission, the
Council, the Parliament or any other institution, body, office or agency of the European Union.
All views expressed are the author's own.</p>
<p class="sf-advice">Nothing here is legal advice. Primary legal texts should be consulted in
their consolidated versions on EUR-Lex, and any live matter should be taken to a qualified
adviser in the relevant jurisdiction.</p>
<p class="sf-reuse"><b>Reuse.</b> No licence has yet been declared for this site, so ordinary
copyright applies to the analysis and the datasets by default. Quotations from and links to EU
legal texts and Commission documents are governed by those documents' own reuse terms, which
this site neither extends nor restricts.</p>
<p class="sf-meta"><span>&copy; 2026</span><span class="sf-sep"></span><span>Facts and dates are
held in <code>data/*.json</code>; every claim carries its own evidence grade.</span></p>
</div>
</footer>`;

export const NOSCRIPT = `<noscript>
<div class="noscript-note">
<p><b>JavaScript is off, so parts of this page are not showing.</b> The written analysis is in
the HTML and reads normally without scripting. What will not appear: the state-of-play ledger,
the regulatory status strips, the compliance calendar, the evidence markers and their drawer,
the comparison tables, the interactions view, search and the glossary panel — all of which are
rendered from <code>data/*.json</code> at runtime.</p>
<p>Every figure behind them is in that directory and can be read directly.</p>
</div>
</noscript>`;

const PAGES = [
  'index.html', 'instruments.html', 'instrument.html', 'institutions.html',
  'enforcement.html', 'applies.html', 'bibliography.html',
];

const BEGIN = '<!-- site-footer:begin — generated by tools/_footer.mjs, do not edit in place -->';
const END = '<!-- site-footer:end -->';
const NBEGIN = '<!-- noscript:begin — generated by tools/_footer.mjs, do not edit in place -->';
const NEND = '<!-- noscript:end -->';

const block = (b, body, e) => `${b}\n${body}\n${e}`;

function upsert(src, begin, end, body, place) {
  const b = src.indexOf(begin);
  if (b !== -1) {
    const e = src.indexOf(end, b);
    return src.slice(0, b) + block(begin, body, end) + src.slice(e + end.length);
  }
  return place(src, block(begin, body, end));
}

let touched = 0;
for (const file of PAGES) {
  let s = readFileSync(file, 'utf8');
  const before = s;

  /* the notice goes immediately after <body> so a reader without scripting
     meets it before anything that silently failed to render */
  s = upsert(s, NBEGIN, NEND, NOSCRIPT, (t, blk) =>
    t.replace(/(<body[^>]*>)/, `$1\n${blk}`));

  /* the footer goes last inside <body>, after every script tag it does not
     depend on */
  s = upsert(s, BEGIN, END, FOOTER, (t, blk) =>
    t.replace(/<\/body>/, `${blk}\n</body>`));

  if (s !== before) { writeFileSync(file, s); touched++; }
  console.log(`  ${file} ${s !== before ? 'updated' : 'unchanged'}`);
}
console.log(`\n${touched} file(s) written.`);

/* ---------------------------------------------------------- social meta

   Title and description are not retyped here: they are read out of each
   page's existing <title> and meta[name=description], so the social card
   cannot say something different from the page. There is no og:image
   because there is no image; twitter:card is therefore "summary" and not
   "summary_large_image", which would promise a picture that does not
   exist. */

const SITE_NAME = 'The European Legal Framework for the Digital World';
const SBEGIN = '<!-- social-meta:begin — generated by tools/_footer.mjs, do not edit in place -->';
const SEND = '<!-- social-meta:end -->';
const attr = (s) => String(s).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');

export function socialMeta(file, src) {
  const title = (src.match(/<title>([\s\S]*?)<\/title>/) || [, file])[1].trim();
  const desc = (src.match(/<meta content="([^"]*)" name="description"\/>/) || [, ''])[1];
  const url = BASE + (file === 'index.html' ? '' : file);
  return [
    `<link href="${url}" rel="canonical"/>`,
    `<meta content="${attr(title)}" property="og:title"/>`,
    `<meta content="${desc}" property="og:description"/>`,
    '<meta content="article" property="og:type"/>',
    `<meta content="${url}" property="og:url"/>`,
    `<meta content="${attr(SITE_NAME)}" property="og:site_name"/>`,
    '<meta content="en" property="og:locale"/>',
    '<meta content="summary" name="twitter:card"/>',
    `<meta content="${attr(title)}" name="twitter:title"/>`,
    `<meta content="${desc}" name="twitter:description"/>`,
  ].join('\n');
}

for (const file of PAGES) {
  let s = readFileSync(file, 'utf8');
  const before = s;
  s = upsert(s, SBEGIN, SEND, socialMeta(file, s), (t, blk) =>
    t.replace('<link href="css/tokens.css" rel="stylesheet"/>',
      `${blk}\n<link href="css/tokens.css" rel="stylesheet"/>`));
  if (s !== before) writeFileSync(file, s);
}
console.log('social meta regenerated from each page\'s own title and description.');
