/* ============================================================
   tools/csp.mjs — the Content-Security-Policy, in one place

   GitHub Pages cannot send response headers, so the policy travels as a
   <meta http-equiv="Content-Security-Policy"> in every page. That has two
   consequences this module is arranged around:

   1. A meta policy only governs what comes AFTER it in the document, so it
      is placed immediately after <meta charset>, ahead of every script and
      stylesheet. `tools/_footer.mjs` writes it there.
   2. Some directives are ignored in a meta policy — frame-ancestors,
      report-uri, sandbox — and some headers cannot be sent at all:
      X-Content-Type-Options, Permissions-Policy, Strict-Transport-Security,
      X-Frame-Options. They are NOT claimed here. docs/DEPLOYMENT.md says
      which protections exist, which are meta-only, and which need a host
      that can set headers.

   WHAT THE POLICY SAYS
     scripts   'self' plus the SHA-256 of each inline <script> on that page
               — the pre-paint theme bootstrap and, on the brief, the
               __CONTENT__ blob. No 'unsafe-inline', no 'unsafe-eval':
               js/evidence-model.js reads derivation formulas with its own
               arithmetic parser for exactly this reason, and the three
               inline onclick="" handlers were moved into app.js.
     styles    'self' 'unsafe-inline'. A deliberate trade-off: several
               modules build markup carrying style="…" attributes, and a
               style attribute cannot execute code. Removing it is future
               work, not a claim made here.
     network   connect-src 'self' — the only fetch is js/data.js loading
               data/*.json and i18n/*. No third-party origin anywhere,
               which tools/thirdparty.mjs already enforces in the source.
     rest      img 'self' data: (the SVG favicon is a data: URL), fonts
               'self', no objects, no frames, no workers, base-uri and
               form-action 'self'.

   tools/design-qa.mjs imports this module and fails a page whose inline
   script is not hashed in its own policy — which is what would otherwise
   happen silently, in the browser, the day someone edits the theme
   bootstrap or the __CONTENT__ blob without regenerating.
   ============================================================ */

import { createHash } from 'node:crypto';

export const SBEGIN = '<!-- security-meta:begin — generated by tools/_footer.mjs, do not edit in place -->';
export const SEND = '<!-- security-meta:end -->';

/** The exact text of every classic inline <script> — no src, executable type. */
export function inlineScripts(html) {
  const out = [];
  for (const m of html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)) {
    const attrs = m[1];
    if (/\bsrc\s*=/.test(attrs)) continue;
    const type = (attrs.match(/\btype\s*=\s*["']?([^"'\s>]+)/i) || [])[1];
    /* a data block (JSON-LD) is not executed, and CSP does not govern it */
    if (type && !/^(text\/javascript|module|application\/javascript)$/i.test(type)) continue;
    out.push(m[2]);
  }
  return out;
}

export const sha256 = (s) => `'sha256-${createHash('sha256').update(s, 'utf8').digest('base64')}'`;

/** The policy for one page, given that page's HTML. */
export function policyFor(html) {
  const hashes = [...new Set(inlineScripts(html).map(sha256))];
  return [
    "default-src 'self'",
    `script-src 'self' ${hashes.join(' ')}`.trim(),
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data:",
    "font-src 'self'",
    "connect-src 'self'",
    "object-src 'none'",
    "frame-src 'none'",
    "worker-src 'none'",
    "manifest-src 'self'",
    "base-uri 'self'",
    "form-action 'self'",
  ].join('; ');
}

export const REFERRER = 'strict-origin-when-cross-origin';

export function securityMeta(html) {
  return [
    `<meta http-equiv="Content-Security-Policy" content="${policyFor(html)}"/>`,
    `<meta content="${REFERRER}" name="referrer"/>`,
  ].join('\n');
}

/** What design-qa reports about one page. Empty when the page is sound. */
export function cspProblems(html) {
  const out = [];
  const m = html.match(/<meta http-equiv="Content-Security-Policy" content="([^"]*)"\/>/);
  if (!m) return ['no Content-Security-Policy meta — run node tools/_footer.mjs'];
  const policy = m[1];
  const charset = html.search(/<meta charset=/i);
  const first = html.search(/<script\b|<link\b[^>]*stylesheet/i);
  if (html.indexOf(m[0]) < charset || (first !== -1 && html.indexOf(m[0]) > first)) {
    out.push('the CSP meta must follow <meta charset> and precede every script and stylesheet, or it does not govern them');
  }
  const scriptSrc = (policy.match(/script-src ([^;]*)/) || [, ''])[1];
  if (/'unsafe-inline'|'unsafe-eval'/.test(scriptSrc)) out.push(`script-src allows ${scriptSrc.match(/'unsafe-[a-z]+'/g).join(', ')}`);
  for (const s of inlineScripts(html)) {
    if (!scriptSrc.includes(sha256(s))) out.push(`an inline script (${s.trim().slice(0, 40).replace(/\s+/g, ' ')}…) is not hashed in the policy, so the browser will refuse to run it — run node tools/_footer.mjs`);
  }
  if (policy !== policyFor(html)) out.push('the policy differs from the one tools/csp.mjs derives for this page — run node tools/_footer.mjs');
  return out;
}
