#!/usr/bin/env node
/* ============================================================
   tools/og-image.mjs — the social preview images, rendered locally

   docs/SEO-AUDIT-2026-09-27.md A7: no page had an og:image, so every
   share of this site was a grey text card. A preview image has to be a
   raster file (the platforms that read Open Graph do not render SVG),
   hosted on the site itself (no third-party image service — the site
   makes no third-party request, and an image URL on someone else's
   host is one).

   So the cards are drawn here, in the site's own typefaces and palette,
   by the Chromium this repository already drives for its browser suite
   (agent/browser/cdp.mjs — no Playwright, no dependency), and committed
   as PNGs under img/og/:

     img/og/site.png        every top-level page
     img/og/<id>.png        each instrument page (tools/seo.mjs routes)

   WHAT A CARD SAYS. Identity only: the name, the full title of the act,
   its kind and CELEX number — facts that do not change with the
   calendar. No status, no date, no count: an image cannot be corrected
   by a validator the way text can, so it carries nothing that goes
   stale on its own.

   STALENESS. A PNG cannot be regenerated byte-for-byte on another
   machine (font rasterisation differs between Chromium builds), so the
   check is on the INPUT: img/og/manifest.json records the SHA-256 of the
   HTML each card was drawn from, and tools/seo-audit.mjs recomputes that
   HTML from the data and fails when it differs — the card no longer
   says what the record says.

   Usage:  node tools/og-image.mjs          render every card, write the manifest
           node tools/og-image.mjs --check  exit 1 if a card is missing or stale
   ============================================================ */

import { createHash } from 'node:crypto';
import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { label as taxLabel } from '../js/data.js';
import { SITE, loadDb, buildRoutes, displayName, ROOT } from './seo.mjs';

export const OUT_DIR = 'img/og';
export const MANIFEST = 'img/og/manifest.json';
export const W = 1200;
export const H = 630;

const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

/* The night palette and the three typefaces of style.css, restated for a
   file that is not a page of the site. The values are copied, not
   invented; tools/seo-audit.mjs does not read them, and if the palette
   changes the cards simply keep the old one until someone re-renders. */
const CARD_CSS = `
@font-face{font-family:'Fraunces';font-weight:300 900;src:url('fonts/fraunces-variable.woff2') format('woff2')}
@font-face{font-family:'Literata';font-weight:400;src:url('fonts/literata-400.woff2') format('woff2')}
@font-face{font-family:'IBM Plex Mono';font-weight:500;src:url('fonts/plexmono-500.woff2') format('woff2')}
*{box-sizing:border-box;margin:0;padding:0}
html,body{width:${W}px;height:${H}px;background:#14111B;color:#EDE4D4;overflow:hidden}
.card{position:relative;width:100%;height:100%;padding:72px 84px;display:flex;flex-direction:column;
  border:1px solid #382F45;background:radial-gradient(ellipse at 88% 12%,#262032 0%,#14111B 60%)}
.rule{position:absolute;left:84px;right:84px;bottom:132px;height:1px;background:#382F45}
.mark{position:absolute;right:84px;top:64px;width:72px;height:72px;border:3px solid #D9A93C;border-radius:50%}
.mark::after{content:'';position:absolute;left:50%;top:-10px;width:18px;height:18px;margin-left:-9px;border-radius:50%;background:#D9A93C}
.kicker{font-family:'IBM Plex Mono',monospace;font-weight:500;font-size:22px;letter-spacing:.14em;text-transform:uppercase;color:#D9A93C}
h1{font-family:'Fraunces',Georgia,serif;font-weight:600;font-size:88px;line-height:1.02;margin-top:40px;max-width:900px;letter-spacing:-.01em}
h1.long{font-size:68px}
.sub{font-family:'Literata',Georgia,serif;font-size:30px;line-height:1.35;color:#B8AC98;margin-top:28px;max-width:960px}
.foot{position:absolute;left:84px;right:84px;bottom:64px;display:flex;justify-content:space-between;
  gap:32px;font-family:'IBM Plex Mono',monospace;font-weight:500;font-size:21px;letter-spacing:.08em;text-transform:uppercase;color:#978C7E}
.foot b{color:#EDE4D4;font-weight:500}
`;

function card({ kicker, title, sub, left, right }) {
  return `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><style>${CARD_CSS}</style></head>` +
    `<body><div class="card"><div class="mark"></div><p class="kicker">${esc(kicker)}</p>` +
    `<h1${title.length > 26 ? ' class="long"' : ''}>${esc(title)}</h1><p class="sub">${esc(sub)}</p>` +
    `<div class="rule"></div><div class="foot"><span>${left}</span><span>${right}</span></div></div></body></html>`;
}

/** Every card the site needs, as { file, html }, derived from the routes. */
export function cards(root = ROOT) {
  const db = loadDb(root);
  const { routes, ix } = buildRoutes(db, root);
  const out = [{
    file: SITE.image.path,
    html: card({
      kicker: SITE.name,
      title: SITE.alternateName,
      sub: 'The EU digital rulebook — ' + routes.filter((r) => r.kind === 'instrument').slice(0, 6)
        .map((r) => ix.instrument.get(r.id).short_name).join(' · ') + ' — read as law, as record and as argument.',
      left: 'Every claim graded by its evidence',
      right: 'Independent analysis',
    }),
  }];
  for (const r of routes.filter((x) => x.kind === 'instrument')) {
    const inst = ix.instrument.get(r.id);
    out.push({
      file: r.image.path,
      html: card({
        kicker: SITE.name + ' · Instrument',
        title: displayName(inst),
        sub: inst.full_name,
        left: esc(taxLabel(ix, inst.kind)) + (inst.celex ? ' · <b>CELEX ' + esc(inst.celex) + '</b>' : ''),
        right: 'Graded record',
      }),
    });
  }
  return out;
}

export const sha = (s) => createHash('sha256').update(s, 'utf8').digest('hex');

/** Cards missing, stale against the manifest, or not in it. Empty = current. */
export function staleCards(root = ROOT) {
  const man = existsSync(join(root, MANIFEST)) ? JSON.parse(readFileSync(join(root, MANIFEST), 'utf8')) : { cards: {} };
  const out = [];
  for (const c of cards(root)) {
    const rec = man.cards && man.cards[c.file];
    if (!existsSync(join(root, c.file))) out.push(`${c.file} is missing`);
    else if (!rec) out.push(`${c.file} is not in ${MANIFEST}`);
    else if (rec.input_sha256 !== sha(c.html)) out.push(`${c.file} was drawn from different data — re-run node tools/og-image.mjs`);
    else {
      const png = readFileSync(join(root, c.file));
      const w = png.readUInt32BE(16), h = png.readUInt32BE(20);
      if (png.toString('ascii', 1, 4) !== 'PNG' || w !== W || h !== H) out.push(`${c.file} is not a ${W}×${H} PNG`);
    }
  }
  return out;
}

async function render(root = ROOT) {
  const { findBrowser } = await import('../agent/browser/find.mjs');
  const { launch, sleep } = await import('../agent/browser/cdp.mjs');
  const { serveSite } = await import('../agent/browser/serve.mjs');
  const found = findBrowser();
  if (!found.found) { console.error('tools/og-image.mjs: no Chromium found — ' + found.reason); process.exit(2); }

  const list = cards(root);
  const stage = mkdtempSync(join(tmpdir(), 'og-'));
  cpSync(join(root, 'fonts'), join(stage, 'fonts'), { recursive: true });
  list.forEach((c, i) => writeFileSync(join(stage, `card-${i}.html`), c.html));

  const site = await serveSite({ root: stage });
  const browser = await launch({ executable: found.path });
  const manifest = { $description: 'The input each social preview card was drawn from, by SHA-256. tools/seo-audit.mjs recomputes it from the data; a mismatch means the card no longer says what the record says. Written by tools/og-image.mjs.', width: W, height: H, cards: {} };
  try {
    const page = await browser.newPage();
    await page.send('Emulation.setDeviceMetricsOverride', { width: W, height: H, deviceScaleFactor: 1, mobile: false });
    for (let i = 0; i < list.length; i++) {
      const c = list[i];
      await page.goto(`${site.origin}/card-${i}.html`);
      await page.evaluate('document.fonts.ready.then(() => true)');
      await sleep(150);
      const shot = await page.send('Page.captureScreenshot', { format: 'png', clip: { x: 0, y: 0, width: W, height: H, scale: 1 } });
      mkdirSync(dirname(join(root, c.file)), { recursive: true });
      writeFileSync(join(root, c.file), Buffer.from(shot.data, 'base64'));
      manifest.cards[c.file] = { input_sha256: sha(c.html) };
      console.log('  ' + c.file);
    }
  } finally {
    await browser.close();
    await site.close?.();
    rmSync(stage, { recursive: true, force: true });
  }
  writeFileSync(join(root, MANIFEST), JSON.stringify(manifest, null, 2) + '\n');
  console.log(`${list.length} card(s) rendered; ${MANIFEST} written.`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  if (process.argv.includes('--check')) {
    const p = staleCards();
    for (const x of p) console.log('  STALE  ' + x);
    console.log(p.length ? `${p.length} card(s) out of date` : 'every social card is current');
    process.exit(p.length ? 1 : 0);
  }
  render().then(() => process.exit(0), (e) => { console.error(e); process.exit(1); });
}
