/* ============================================================
   tools/prose-homes.mjs — the text a page shows has one home: its markup

   Until 30 Sep 2026 index.html carried its own prose twice. The markup
   held what a reader sees; an inline <script> assigned a 67 KB object,
   window.__CONTENT__, holding the part titles, the deks, a standfirst and
   a plain-text copy of every Part, and app.js read its contents overlay,
   its pagers and its search index from THAT. The generator that wrote the
   object was never committed, so every later edit went into the markup, or
   into both copies by hand, or into the copy nobody renders. By the time it
   was removed it had lost Annex C and about 9 KB of the current prose, and
   search quoted a brief that no longer existed. docs/CURRENT-ARCHITECTURE.md
   §8 has the history.

   The remedy was to delete the copy, not to synchronise it: app.js now
   reads the Parts out of the markup it is loaded into. This module is what
   keeps it deleted. It asserts one structural invariant:

     NO SCRIPT CARRIES A PAGE'S OWN TEXT.

   For every hand-written page, each block of text a reader meets — a
   heading, paragraph, list item, caption or cell of at least MIN_WORDS
   words — is looked for in every script that could hold a second copy:
   the page's own inline <script> blocks, of any type, and every module
   the site ships (js/*.js and app.js). A hit is a second, hand-editable
   home for a sentence that already has one.

   It does not look for a name. A blob reintroduced as window.__BRIEF__, as
   <script type="application/json">, or as a string table in a new module is
   caught the same way, because what is detected is the duplicated TEXT.

   WHAT IS NOT A SECOND HOME, AND WHY IT IS SKIPPED
     · Text inside a region tools/_footer.mjs generates (`<!-- x:begin —
       generated by tools/_footer.mjs …-->`). That is derived output; its
       source is data/ or the nav model, and _footer.mjs rewrites it.
     · The pages under instruments/<id>/. Each is generated whole from
       data/ by tools/_footer.mjs through js/instrument-view.js, and
       tools/seo-audit.mjs fails the build when one is stale.
     · JSON-LD. It is generated from tools/seo.mjs into social-meta and
       is a description of the page for a crawler, not a copy of its prose.
     · Comments in a module. A comment that quotes the prose it works on
       is documentation; nothing renders it.
     · Text with fewer than MIN_WORDS words. A label such as "Contents" or
       "Next" is interface vocabulary a module legitimately writes too.

   WHAT IT DOES NOT PROVE. That a sentence written in the markup is true;
   that data/brief.json's part titles agree with the headings (they are a
   second home this check does not cover — docs/CURRENT-ARCHITECTURE.md §8
   names it as the remaining one); or anything about the it/fr/es overlays,
   which are declared translations with their own register.
   ============================================================ */

import { readFileSync, readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';

/** Blocks shorter than this are interface vocabulary, not prose. Six is
 *  the threshold agent/proposals/editorial/prose.mjs already uses for
 *  "a block below the line is a label". */
export const MIN_WORDS = 6;

const GENERATED = /<!-- ([a-z-]+):begin — generated by tools\/_footer\.mjs[^>]*-->[\s\S]*?<!-- \1:end -->/g;

const ENTITIES = { amp: '&', lt: '<', gt: '>', quot: '"', apos: '\'', nbsp: ' ' };
const decode = (s) => s
  .replace(/&#(\d+);/g, (_, n) => String.fromCodePoint(Number(n)))
  .replace(/&#x([0-9a-f]+);/gi, (_, n) => String.fromCodePoint(parseInt(n, 16)))
  .replace(/&([a-z]+);/gi, (m, n) => ENTITIES[n.toLowerCase()] ?? m);

/** Letters and digits only, lower-cased. A copy is the same words in the
 *  same order; how a script escapes a quote or joins two blocks is not what
 *  makes it a copy. */
export const fold = (s) => String(s).toLowerCase().replace(/[^\p{L}\p{N}]+/gu, '');

/** The hand-written text of a page: its markup with scripts, comments,
 *  <noscript> and every generated region removed, cut into the blocks a
 *  reader meets. */
export function textBlocks(html) {
  const authored = html
    .replace(GENERATED, ' ')
    .replace(/<script\b[\s\S]*?<\/script>/gi, ' ')
    .replace(/<noscript\b[\s\S]*?<\/noscript>/gi, ' ')
    .replace(/<!--[\s\S]*?-->/g, ' ');
  const out = new Set();
  for (const m of authored.matchAll(/<(h[1-6]|p|li|figcaption|caption|td|th|dt|dd|blockquote)\b[^>]*>([\s\S]*?)<\/\1>/gi)) {
    const text = decode(m[2].replace(/<[^>]+>/g, ' ')).replace(/\s+/g, ' ').trim();
    if (text.split(' ').length >= MIN_WORDS) out.add(text);
  }
  return [...out];
}

/** Every <script> body on a page that could hold a copy: no src, and not
 *  the generated JSON-LD. Any other type counts — a JSON data block is
 *  exactly how a blob would come back without being executable. */
export function scriptBodies(html) {
  const out = [];
  for (const m of html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)) {
    if (/\bsrc\s*=/i.test(m[1])) continue;
    if (/\btype\s*=\s*["']?application\/ld\+json/i.test(m[1])) continue;
    out.push(m[2]);
  }
  return out;
}

/** A module's code without its comments. Block comments go whole; a line
 *  comment only where it starts the line, because a `//` inside a string —
 *  a URL — is not a comment, and stripping from it to the end of the line
 *  would hide the rest of a one-line blob from this check. */
export const codeOf = (src) => String(src).replace(/\/\*[\s\S]*?\*\//g, ' ').replace(/^\s*\/\/.*$/gm, ' ');

/** A script's string escapes read back, so that `\u2014` is compared as
 *  the dash it stands for. JSON written with every non-ASCII character
 *  escaped would otherwise hide every sentence carrying one. */
export const unescapeJs = (s) => String(s)
  .replace(/\\u\{([0-9a-f]{1,6})\}|\\u([0-9a-f]{4})/gi, (_, braced, bare) => String.fromCodePoint(parseInt(braced ?? bare, 16)));

/** The hand-written pages: every .html at the root. instruments/ is
 *  generated whole and is deliberately not here (see the header). */
export const authoredPages = (root) => readdirSync(root).filter((f) => f.endsWith('.html')).sort();

/** Every module the site ships to a browser. */
export function siteModules(root) {
  const js = existsSync(join(root, 'js'))
    ? readdirSync(join(root, 'js')).filter((f) => f.endsWith('.js')).sort().map((f) => `js/${f}`)
    : [];
  return existsSync(join(root, 'app.js')) ? [...js, 'app.js'] : js;
}

/**
 * Every block of a page's text that a script also holds.
 *
 * @param {string} root  the repository root, as sitePages() takes it
 * @returns {{page:string, file:string, text:string}[]} one entry per
 *   duplicated block and holder; `file` is the page itself for an inline
 *   script, or the module's path.
 */
export function proseCopies(root) {
  const modules = siteModules(root).map((file) => ({ file, code: fold(unescapeJs(codeOf(readFileSync(join(root, file), 'utf8')))) }));
  const found = [];
  for (const page of authoredPages(root)) {
    const html = readFileSync(join(root, page), 'utf8');
    const holders = [
      ...scriptBodies(html).map((body) => ({ file: page, code: fold(unescapeJs(body)) })),
      ...modules,
    ];
    for (const text of textBlocks(html)) {
      const key = fold(text);
      if (!key) continue;
      for (const h of holders) if (h.code.includes(key)) found.push({ page, file: h.file, text });
    }
  }
  return found;
}
